# Generated by Django 4.1.5 on 2023-03-28 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEdition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='network.post')),
            ],
        ),
    ]
