# Generated by Django 4.1.5 on 2023-03-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_postedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postedition',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
