# Generated by Django 4.1.5 on 2023-03-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_follow_id_alter_like_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change', to='network.like')),
            ],
        ),
    ]
