# Generated by Django 4.1.5 on 2023-03-28 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_likechange'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostEdition',
        ),
    ]
