# Generated by Django 4.1.5 on 2023-03-28 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_delete_postedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=4096)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='network.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='likeUnlike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='likechange',
            name='likeUnlike',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likechange',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeChange', to='network.like'),
        ),
        migrations.CreateModel(
            name='PostEdition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=4096)),
                ('timestamp', models.DateTimeField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='network.post')),
            ],
        ),
        migrations.CreateModel(
            name='FollowChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('followUnfollow', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followChange', to='network.follow')),
            ],
        ),
        migrations.CreateModel(
            name='CommentChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=4096)),
                ('timestamp', models.DateTimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change', to='network.comment')),
            ],
        ),
    ]
